import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f1",
  },
  appRoot: {
    flex: 1,
    backgroundColor: "#f5f1edff",
  },
  dropdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9,
  },
  mobileTopBar: {
    backgroundColor: "#faf6f1f2",
    borderBottomWidth: 1,
    borderBottomColor: "#cde3db",
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoBox: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1a7f7f",
  },
  logoText: {
    color: "#faf6f1",
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "800",
  },
  brandOverline: {
    color: "#8193ac",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  brandTitle: {
    color: "#0f274d",
    fontWeight: "700",
    fontSize: 14,
  },
  profileChip: {
    borderWidth: 1,
    borderColor: "#bfd5cc",
    backgroundColor: "#faf6f1",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  profileChipActive: {
    borderColor: "#4a9f9f",
    backgroundColor: "#e6f5f4",
  },
  profileChipText: {
    fontSize: 12,
    color: "#5d7089",
    fontWeight: "600",
  },
  headerRightSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  boatSwitcherWrapper: {
    position: "relative",
  },
  boatSwitcherChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: 176,
  },
  boatSwitcherChipText: {
    maxWidth: 132,
  },
  dropdownArrow: {
    fontSize: 10,
    color: "#5d7089",
  },
  pickerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0,
    width: "100%",
    height: "100%",
    ...Platform.select({
      web: {
        cursor: "pointer",
      } as any,
    }),
  },
  boatDropdown: {
    position: "absolute",
    top: 38,
    right: 0,
    backgroundColor: "#faf6f1",
    borderWidth: 1,
    borderColor: "#bfd5cc",
    borderRadius: 8,
    zIndex: 100,
    minWidth: 160,
    shadowColor: "#1a7f7f",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  boatDropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebe9",
  },
  boatDropdownItemActive: {
    backgroundColor: "#e6f5f4",
  },
  boatDropdownItemText: {
    fontSize: 13,
    color: "#5d7089",
    fontWeight: "500",
  },
  boatDropdownItemTextActive: {
    color: "#1a7f7f",
    fontWeight: "600",
  },
  pageScrollContent: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    paddingBottom: 110,
    gap: 12,
  },
  pageHeader: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-end",
  },
  pageTitle: {
    color: "#0f284e",
    fontSize: 26,
    fontWeight: "700",
  },
  pageSub: {
    color: "#60748e",
    fontSize: 13,
    marginTop: 2,
  },
  card: {
    borderWidth: 1,
    borderColor: "#cde3db",
    backgroundColor: "#faf6f1ee",
    borderRadius: 16,
    padding: 14,
  },
  cardTitle: {
    color: "#102949",
    fontSize: 15,
    fontWeight: "700",
  },
  cardSub: {
    color: "#6b8099",
    fontSize: 12,
    marginTop: 3,
  },
  cardBody: {
    marginTop: 10,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    width: "48%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#cde3db",
    backgroundColor: "#faf6f1ee",
    padding: 12,
  },
  statLabel: {
    color: "#697b93",
    fontSize: 11,
  },
  statValue: {
    color: "#102949",
    fontSize: 24,
    fontWeight: "700",
    marginTop: 6,
  },
  statCaption: {
    color: "#8ea0b6",
    fontSize: 11,
  },
  statCardPending: {
    borderColor: "#fca5a5",
    backgroundColor: "#ffe8e8",
  },
  listCard: {
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  listCardPressed: {
    opacity: 0.82,
    borderColor: "#4a9f9f",
  },
  rowBetweenTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  listCardTitle: {
    color: "#0f2748",
    fontWeight: "600",
    fontSize: 14,
  },
  listCardSub: {
    color: "#64788f",
    fontSize: 12,
    marginTop: 2,
  },
  listCardMeta: {
    color: "#546b86",
    fontSize: 13,
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "600",
  },
  bookingSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  expandIcon: {
    fontSize: 12,
    color: "#6a7f97",
    fontWeight: "600",
  },
  bookingDetailsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e8ebe9",
  },
  expandableBookingCard: {
    marginBottom: 0,
  },
  rowGap8: {
    flexDirection: "row",
    gap: 8,
  },
  outlineButton: {
    borderWidth: 1,
    borderColor: "#bfd5cc",
    borderRadius: 8,
    backgroundColor: "#faf6f1",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  outlineButtonText: {
    color: "#5d7289",
    fontSize: 12,
    fontWeight: "600",
  },
  softBlueButton: {
    borderWidth: 1,
    borderColor: "#4a9f9f",
    borderRadius: 8,
    backgroundColor: "#e6f5f4",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  softBlueButtonText: {
    color: "#1a7f7f",
    fontSize: 12,
    fontWeight: "600",
  },
  verticalGap10: { gap: 10 },
  verticalGap8: { gap: 8 },
  verticalGap12: { gap: 12 },
  metaBox: {
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#f5f2ed",
  },
  metaLabel: {
    color: "#6a7f97",
    fontSize: 11,
  },
  metaValue: {
    color: "#0f284d",
    fontSize: 14,
    marginTop: 4,
    fontWeight: "500",
  },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#bfd5cc",
    borderRadius: 9,
    backgroundColor: "#faf6f1",
    color: "#102949",
    fontSize: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  selectButton: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#bfd5cc",
    borderRadius: 9,
    backgroundColor: "#faf6f1",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  selectButtonDisabled: { backgroundColor: "#ebe8e3" },
  selectButtonText: {
    color: "#13345a",
    fontSize: 13,
    fontWeight: "500",
  },
  selectButtonTextDisabled: { color: "#7d8fa4" },
  featureRow: {
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 10,
    backgroundColor: "#faf6f1",
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  featureRowText: { color: "#234058", fontSize: 13 },
  pillWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  featurePill: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  featurePillEnabled: { borderColor: "#4a9f9f", backgroundColor: "#e6f5f4" },
  featurePillDisabled: { borderColor: "#bfd5cc", backgroundColor: "#eff4f9" },
  featurePillEnabledText: { color: "#1a7f7f", fontSize: 11, fontWeight: "600" },
  featurePillDisabledText: { color: "#6f8195", fontSize: 11, fontWeight: "600" },
  cruisePillEnabled: { borderColor: "#9dd8bc", backgroundColor: "#dcfce8" },
  cruisePillDisabled: { borderColor: "#bfd5cc", backgroundColor: "#eff4f9" },
  cruisePillEnabledText: { color: "#0f7a4f", fontSize: 11, fontWeight: "600" },
  cruisePillDisabledText: { color: "#6f8195", fontSize: 11, fontWeight: "600" },
  innerPanel: { borderWidth: 1, borderColor: "#cde3db", borderRadius: 12, padding: 10 },
  innerPanelTitle: { color: "#102949", fontSize: 13, fontWeight: "600", marginBottom: 8 },
  fieldLabel: { color: "#6a7f97", fontSize: 11 },
  calendarGrid: { gap: 4, flex: 1 },
  calendarWeekRow: { flexDirection: "row", gap: 4, flex: 1 },
  dayCell: {
    flex: 1,
    flexBasis: 0,
    minHeight: 64,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "flex-start",
    borderWidth: 1,
  },
  dayCellFull: { backgroundColor: "#ffe5e5", borderColor: "#ffcccc" },
  dayCellPartial: { backgroundColor: "#fff1d6", borderColor: "#f5d392" },
  dayCellEmpty: { backgroundColor: "#dbf8ea", borderColor: "#9dd8bc" },
  dayCellSelected: { borderColor: "#1a7f7f", borderWidth: 2 },
  dayCellBulkSelected: {
    borderColor: "#1a7f7f",
    borderWidth: 2,
    backgroundColor: "#e6f5f4",
    shadowColor: "#1a7f7f",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.24,
    shadowRadius: 4,
    elevation: 3,
  },
  dayCellBlank: { flex: 1, flexBasis: 0, minHeight: 64 },
  dayCellNumber: { fontSize: 11, fontWeight: "600", color: "#1d3450" },
  dayCellCruiseRows: { width: "100%", gap: 2, marginTop: 2 },
  dayCellCruiseRow: { flexDirection: "row", alignItems: "center", gap: 3 },
  dayCellCruisePrice: { flex: 1, fontSize: 9, color: "#1a7f7f", fontWeight: "700" },
  dayCellTickPlaceholder: { width: 7, height: 7 },
  bulkCheckBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#1a7f7f",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarPageRoot: { flex: 1 },
  cruisePriceRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 10,
    backgroundColor: "#faf6f1",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  cruiseCombinedRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 10,
    backgroundColor: "#faf6f1",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  cruisePriceLabel: { color: "#234058", fontSize: 13, flex: 1 },
  cruisePriceField: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#bfd5cc",
    borderRadius: 9,
    backgroundColor: "#f5f2ed",
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 4,
    minWidth: 90,
  },
  bulkPricingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 12,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e8f0f8",
  },
  bulkPricingTextBlock: { flex: 1 },
  bulkPricingLabel: { color: "#102949", fontSize: 13, fontWeight: "600" },
  bulkPricingSubLabel: { color: "#6b8099", fontSize: 11, marginTop: 1 },
  bulkToggleButton: {
    borderWidth: 1,
    borderColor: "#bfd5cc",
    borderRadius: 8,
    backgroundColor: "#faf6f1",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  bulkToggleButtonCancel: { borderColor: "#4a9f9f", backgroundColor: "#e6f5f4" },
  bulkToggleButtonText: { color: "#5d7289", fontSize: 12, fontWeight: "600" },
  bulkToggleButtonCancelText: { color: "#1a7f7f" },
  bottomSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bottomSheetInfo: { flex: 1 },
  bottomSheetTitle: { color: "#102949", fontSize: 13, fontWeight: "700" },
  bottomSheetSub: { color: "#6b8099", fontSize: 11, marginTop: 1 },
  bottomSheetCloseButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#bfd5cc",
    backgroundColor: "#ebe8e3",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetRupee: { color: "#5a7090", fontSize: 14, fontWeight: "600" },
  bottomSheetInput: { flex: 1, color: "#102949", fontSize: 14, padding: 0 },
  applyPriceButton: {
    borderRadius: 10,
    backgroundColor: "#1a7f7f",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  applyPriceButtonDisabled: { backgroundColor: "#a8c9c5" },
  applyPriceButtonText: { color: "#faf6f1", fontSize: 13, fontWeight: "600" },
  calendarMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  monthChevronButton: {
    width: 30,
    height: 30,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#bfd5cc",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#faf6f1",
  },
  monthChevronText: { color: "#1a7f7f", fontSize: 20, lineHeight: 22, fontWeight: "700" },
  calendarMonthTitle: { color: "#102949", fontSize: 15, fontWeight: "700" },
  weekdayHeaderText: {
    flex: 1,
    textAlign: "center",
    color: "#62768f",
    fontSize: 11,
    fontWeight: "600",
    paddingBottom: 4,
  },
  primaryButton: {
    marginTop: 4,
    borderRadius: 10,
    backgroundColor: "#1a7f7f",
    alignItems: "center",
    paddingVertical: 10,
  },
  primaryButtonText: { color: "#faf6f1", fontSize: 13, fontWeight: "600" },
  calendarRuleText: { color: "#5a6d82", fontSize: 12 },
  bulkPricingPanel: {
    backgroundColor: "#faf6f1",
    borderTopWidth: 1,
    borderTopColor: "#cde3db",
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 96,
    gap: 10,
    shadowColor: "#1a7f7f",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  dayEditPanel: {
    backgroundColor: "#faf6f1",
    borderTopWidth: 1,
    borderTopColor: "#cde3db",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 96,
    gap: 12,
    shadowColor: "#1a7f7f",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  modalDragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#d0dce8",
    alignSelf: "center",
    marginBottom: 4,
  },
  modalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: { color: "#102949", fontSize: 16, fontWeight: "700" },
  requestTabRow: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 12,
    backgroundColor: "#f5f2ed",
    padding: 4,
    gap: 6,
  },
  requestTabButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  requestTabButtonActive: {
    backgroundColor: "#faf6f1",
    borderWidth: 1,
    borderColor: "#4a9f9f",
  },
  requestTabText: { color: "#5d7289", fontSize: 12, fontWeight: "600" },
  requestTabTextActive: { color: "#1a7f7f" },
  inlineWrapRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  inlineMuted: { color: "#6c8098", fontSize: 11 },
  detailText: { marginTop: 10, color: "#5a6d82", fontSize: 13 },
  detailStrong: { marginTop: 8, color: "#334b67", fontSize: 13, fontWeight: "500" },
  detailMuted: { marginTop: 8, color: "#7a8da4", fontSize: 12 },
  acceptButton: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: "#109c61",
    paddingHorizontal: 24,
    paddingVertical: 12,
    flex: 1,
    alignItems: "center",
  },
  declineButton: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: "#cf3850",
    paddingHorizontal: 24,
    paddingVertical: 12,
    flex: 1,
    alignItems: "center",
    marginRight: 8,
  },
  actionButtonText: { color: "#ffffff", fontSize: 13, fontWeight: "600" },
  buttonRowBetween: { flexDirection: "row", gap: 8, marginTop: 10 },
  bookingRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebe9",
    paddingVertical: 6,
    gap: 8,
  },
  bookingRowKey: { color: "#6b8098", fontSize: 12, flex: 1 },
  bookingRowValue: { color: "#193555", fontSize: 12, fontWeight: "500", textAlign: "right", flex: 1 },
  profileBoatRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#cde3db",
    borderRadius: 10,
    backgroundColor: "#f5f2ed",
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileBoatText: { color: "#13345a", fontSize: 13, fontWeight: "500" },
  noteBox: { marginTop: 10, borderRadius: 12, backgroundColor: "#e6f5f4", padding: 10 },
  noteText: { color: "#5a6d82", fontSize: 11, lineHeight: 17 },
  flex1: { flex: 1 },
});

export default styles;
