import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  navy: "#0F172A",
  navyLight: "#475569",
  teal: "#0D9488",
  tealLight: "#CCFBF1",
  tealMedium: "#0F9D94",
  bg: "#F8FAFC",
  border: "#E2E8F0",
  coral: "#F97316",
  pink: "#EC4899",
  white: "#FFFFFF",
  muted: "#64748B",
  amber: "#F59E0B",
  red: "#EF4444",
  green: "#10B981",
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#4a1060",
  },
  appRoot: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  dropdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9,
  },
  mobileTopBar: {
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoBox: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.teal,
  },
  logoText: {
    color: COLORS.white,
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "800",
  },
  brandOverline: {
    color: COLORS.muted,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  brandTitle: {
    color: COLORS.navy,
    fontWeight: "700",
    fontSize: 14,
  },
  profileChip: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    borderRadius: 999,
    height: 38,
    justifyContent: "center",
  },
  profileChipActive: {
    borderColor: "#4a9f9f",
    backgroundColor: COLORS.tealLight,
  },
  profileChipText: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "600",
  },
  headerRightSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  boatSwitcherWrapper: {
    position: "relative",
  },
  boatSwitcherChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: 176,
  },
  boatSwitcherChipText: {
    maxWidth: 132,
  },
  dropdownArrow: {
    fontSize: 10,
    color: COLORS.muted,
  },
  pickerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0,
    width: "100%",
    height: "100%",
    ...Platform.select<Record<string, string>>({
      web: {
        cursor: "pointer",
      },
    }),
  },
  boatDropdown: {
    position: "absolute",
    top: 38,
    right: 0,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    zIndex: 100,
    minWidth: 160,
    shadowColor: COLORS.teal,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  boatDropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebe9",
  },
  boatDropdownItemActive: {
    backgroundColor: COLORS.tealLight,
  },
  boatDropdownItemText: {
    fontSize: 13,
    color: COLORS.muted,
    fontWeight: "500",
  },
  boatDropdownItemTextActive: {
    color: COLORS.teal,
    fontWeight: "600",
  },
  pageScrollContent: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    paddingBottom: 110,
    gap: 12,
  },
  pageHeader: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-end",
  },
  pageTitle: {
    color: COLORS.navy,
    fontSize: 26,
    fontWeight: "700",
  },
  pageSub: {
    color: COLORS.muted,
    fontSize: 13,
    marginTop: 2,
  },
  card: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 14,
  },
  cardTitle: {
    color: COLORS.navy,
    fontSize: 15,
    fontWeight: "700",
  },
  cardSub: {
    color: COLORS.muted,
    fontSize: 12,
    marginTop: 3,
  },
  cardBody: {
    marginTop: 10,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    width: "48%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    padding: 12,
  },
  statLabel: {
    color: COLORS.muted,
    fontSize: 11,
  },
  statValue: {
    color: COLORS.navy,
    fontSize: 24,
    fontWeight: "700",
    marginTop: 6,
  },
  statCaption: {
    color: COLORS.muted,
    fontSize: 11,
  },
  statCardPending: {
    borderColor: "#fca5a5",
    backgroundColor: "#ffe8e8",
  },
  listCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  listCardPressed: {
    opacity: 0.82,
    borderColor: "#4a9f9f",
  },
  rowBetweenTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  listCardTitle: {
    color: COLORS.navy,
    fontWeight: "600",
    fontSize: 14,
  },
  listCardSub: {
    color: "#64788f",
    fontSize: 12,
    marginTop: 2,
  },
  listCardMeta: {
    color: "#546b86",
    fontSize: 13,
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "600",
  },
  bookingSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  expandIcon: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "600",
  },
  bookingDetailsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e8ebe9",
  },
  expandableBookingCard: {
    marginBottom: 0,
  },
  rowGap8: {
    flexDirection: "row",
    gap: 8,
  },
  outlineButton: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  outlineButtonText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  softBlueButton: {
    borderWidth: 1,
    borderColor: "#4a9f9f",
    borderRadius: 8,
    backgroundColor: COLORS.tealLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  softBlueButtonText: {
    color: COLORS.teal,
    fontSize: 12,
    fontWeight: "600",
  },
  verticalGap10: { gap: 10 },
  verticalGap8: { gap: 8 },
  verticalGap12: { gap: 12 },
  metaBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#f5f2ed",
  },
  metaLabel: {
    color: COLORS.muted,
    fontSize: 11,
  },
  metaValue: {
    color: "#0f284d",
    fontSize: 14,
    marginTop: 4,
    fontWeight: "500",
  },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 9,
    backgroundColor: COLORS.white,
    color: COLORS.navy,
    fontSize: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  selectButton: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 9,
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  selectButtonDisabled: { backgroundColor: "#ebe8e3" },
  selectButtonText: {
    color: COLORS.navy,
    fontSize: 13,
    fontWeight: "500",
  },
  selectButtonTextDisabled: { color: "#7d8fa4" },
  featureRow: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  featureRowText: { color: "#234058", fontSize: 13 },
  pillWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  featurePill: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  featurePillEnabled: { borderColor: "#4a9f9f", backgroundColor: COLORS.tealLight },
  featurePillDisabled: { borderColor: COLORS.border, backgroundColor: "#eff4f9" },
  featurePillEnabledText: { color: COLORS.teal, fontSize: 11, fontWeight: "600" },
  featurePillDisabledText: { color: "#6f8195", fontSize: 11, fontWeight: "600" },
  cruisePillEnabled: { borderColor: "#9dd8bc", backgroundColor: "#dcfce8" },
  cruisePillDisabled: { borderColor: COLORS.border, backgroundColor: "#eff4f9" },
  cruisePillEnabledText: { color: "#0f7a4f", fontSize: 11, fontWeight: "600" },
  cruisePillDisabledText: { color: "#6f8195", fontSize: 11, fontWeight: "600" },
  innerPanel: { borderWidth: 1, borderColor: COLORS.border, borderRadius: 12, padding: 10 },
  innerPanelTitle: { color: COLORS.navy, fontSize: 13, fontWeight: "600", marginBottom: 8 },
  fieldLabel: { color: COLORS.muted, fontSize: 11 },
  calendarGrid: { gap: 2, flex: 1 },
  calendarWeekRow: { flexDirection: "row", gap: 2, flex: 1 },
  dayCell: {
    flex: 1,
    flexBasis: 0,
    aspectRatio: 1,
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "flex-start",
    borderWidth: 1,
  },
  dayCellFull: { backgroundColor: "#ffe5e5", borderColor: "#ffcccc" },
  dayCellPartial: { backgroundColor: "#fff1d6", borderColor: "#f5d392" },
  dayCellEmpty: { backgroundColor: "#dbf8ea", borderColor: "#9dd8bc" },
  dayCellSelected: { borderColor: COLORS.teal, borderWidth: 2 },
  dayCellBulkSelected: {
    borderColor: COLORS.teal,
    borderWidth: 2,
    backgroundColor: COLORS.tealLight,
    shadowColor: COLORS.teal,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.24,
    shadowRadius: 4,
    elevation: 3,
  },
  dayCellBlank: {
    flex: 1,
    flexBasis: 0,
    aspectRatio: 1,
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 3,
    borderWidth: 1,
    borderColor: "transparent",
  },
  dayCellNumber: { fontSize: 11, fontWeight: "600", color: COLORS.navy },
  dayCellCruiseRows: { width: "100%", gap: 2, marginTop: 2 },
  dayCellCruiseRow: { flexDirection: "row", alignItems: "center", gap: 3 },
  dayCellCruisePrice: { flex: 1, fontSize: 9, color: COLORS.teal, fontWeight: "700" },
  dayCellTickPlaceholder: { width: 7, height: 7 },
  bulkCheckBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarPageRoot: { flex: 1 },
  cruisePriceRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  cruiseCombinedRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  cruisePriceLabel: { color: "#234058", fontSize: 13, flex: 1 },
  cruisePriceField: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 9,
    backgroundColor: "#f5f2ed",
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 4,
    minWidth: 90,
  },
  bulkPricingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 12,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e8f0f8",
  },
  bulkPricingTextBlock: { flex: 1 },
  bulkPricingLabel: { color: COLORS.navy, fontSize: 13, fontWeight: "600" },
  bulkPricingSubLabel: { color: COLORS.muted, fontSize: 11, marginTop: 1 },
  bulkToggleButton: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  bulkToggleButtonCancel: { borderColor: "#4a9f9f", backgroundColor: COLORS.tealLight },
  bulkToggleButtonText: { color: COLORS.muted, fontSize: 12, fontWeight: "600" },
  bulkToggleButtonCancelText: { color: COLORS.teal },
  bottomSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bottomSheetInfo: { flex: 1 },
  bottomSheetTitle: { color: COLORS.navy, fontSize: 13, fontWeight: "700" },
  bottomSheetSub: { color: COLORS.muted, fontSize: 11, marginTop: 1 },
  bottomSheetCloseButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: "#ebe8e3",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetRupee: { color: COLORS.muted, fontSize: 14, fontWeight: "600" },
  bottomSheetInput: { flex: 1, color: COLORS.navy, fontSize: 14, padding: 0 },
  applyPriceButton: {
    borderRadius: 10,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  applyPriceButtonDisabled: { backgroundColor: "#a8c9c5" },
  applyPriceButtonText: { color: COLORS.white, fontSize: 13, fontWeight: "600" },
  calendarMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  monthChevronButton: {
    width: 48,
    height: 48,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
  },
  monthChevronText: { color: COLORS.teal, fontSize: 28, lineHeight: 28, fontWeight: "700", textAlign: "center" },
  calendarMonthTitle: { color: COLORS.navy, fontSize: 15, fontWeight: "700" },
  weekdayHeaderText: {
    flex: 1,
    textAlign: "center",
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: "600",
    paddingBottom: 4,
  },
  weekdayHeaderTextWeekend: {
    color: "#cf3850",
  },
  primaryButton: {
    marginTop: 4,
    borderRadius: 10,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    paddingVertical: 10,
  },
  primaryButtonText: { color: COLORS.white, fontSize: 13, fontWeight: "600" },
  calendarRuleText: { color: COLORS.muted, fontSize: 12 },
  bulkPricingPanel: {
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    gap: 10,
    shadowColor: COLORS.teal,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  dayEditPanel: {
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 96,
    gap: 12,
    shadowColor: COLORS.teal,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  modalDragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#d0dce8",
    alignSelf: "center",
    marginBottom: 4,
  },
  modalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: { color: COLORS.navy, fontSize: 16, fontWeight: "700" },
  requestTabRow: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    backgroundColor: "#f5f2ed",
    padding: 4,
    gap: 6,
  },
  requestTabButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  requestTabButtonActive: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: "#4a9f9f",
  },
  requestTabText: { color: COLORS.muted, fontSize: 12, fontWeight: "600" },
  requestTabTextActive: { color: COLORS.teal },
  inlineWrapRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  inlineMuted: { color: COLORS.muted, fontSize: 11 },
  detailText: { marginTop: 10, color: COLORS.muted, fontSize: 13 },
  detailStrong: { marginTop: 8, color: "#334b67", fontSize: 13, fontWeight: "500" },
  detailMuted: { marginTop: 8, color: "#7a8da4", fontSize: 12 },
  acceptButton: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: "#109c61",
    paddingHorizontal: 24,
    paddingVertical: 12,
    flex: 1,
    alignItems: "center",
  },
  declineButton: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: "#cf3850",
    paddingHorizontal: 24,
    paddingVertical: 12,
    flex: 1,
    alignItems: "center",
    marginRight: 8,
  },
  actionButtonText: { color: "#ffffff", fontSize: 13, fontWeight: "600" },
  buttonRowBetween: { flexDirection: "row", gap: 8, marginTop: 10 },
  bookingRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebe9",
    paddingVertical: 6,
    gap: 8,
  },
  bookingRowKey: { color: "#6b8098", fontSize: 12, flex: 1 },
  bookingRowValue: { color: COLORS.navy, fontSize: 12, fontWeight: "500", textAlign: "right", flex: 1 },
  profileBoatRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: "#f5f2ed",
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  profileBoatText: { color: COLORS.navy, fontSize: 13, fontWeight: "500" },
  noteBox: { marginTop: 10, borderRadius: 12, backgroundColor: COLORS.tealLight, padding: 10 },
  noteText: { color: COLORS.muted, fontSize: 11, lineHeight: 17 },
  flex1: { flex: 1 },
  boatGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 10,
    marginTop: 4,
  },
  boatCard: {
    width: "48%",
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 130,
  },
  boatCardPressed: {
    opacity: 0.85,
    borderColor: COLORS.teal,
    backgroundColor: COLORS.tealLight,
  },
  boatCardTitle: {
    color: COLORS.navy,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 8,
  },
  miniCalendarContainer: {
    width: "100%",
    alignItems: "center",
  },
  miniCalendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 4,
  },
  miniCalendarHeaderLabel: {
    fontSize: 7,
    fontWeight: "600",
    color: COLORS.muted,
    width: 10,
    textAlign: "center",
  },
  miniCalendarGrid: {
    width: "100%",
    gap: 2,
  },
  miniCalendarWeekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  miniCalendarCell: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    borderWidth: 0.5,
  },
  miniCalendarCellBlank: {
    width: 9,
    height: 9,
    backgroundColor: "transparent",
    borderWidth: 0.5,
    borderColor: "transparent",
  },
  calendarLegendRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    marginTop: 4,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 0.5,
  },
  legendText: {
    fontSize: 10,
    color: COLORS.muted,
    fontWeight: "600",
  },
  /* ── Bottom Sheet (redesigned) ── */
  sheetBackground: {
    backgroundColor: COLORS.bg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  sheetHandleIndicator: {
    backgroundColor: "#c0c8d0",
    width: 36,
    height: 4,
  },
  sheetScroll: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  sheetDateHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingTop: 4,
  },
  sheetDateText: {
    color: COLORS.navy,
    fontSize: 18,
    fontWeight: "700",
  },
  sheetCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#1a2332",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetInfoBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#e8ebe9",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
  },
  sheetInfoText: {
    color: COLORS.muted,
    fontSize: 12,
    flex: 1,
  },
  cruiseCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  cruiseCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  cruiseCardLabel: {
    color: COLORS.navy,
    fontSize: 16,
    fontWeight: "700",
    flex: 1,
  },
  bookedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.teal,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bookedPillText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
  },
  notBookedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#e8ebe9",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  notBookedPillText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  priceFieldsRow: {
    flexDirection: "row",
    gap: 10,
  },
  priceFieldBox: {
    flex: 1,
  },
  priceFieldLabel: {
    color: COLORS.muted,
    fontSize: 13,
    fontWeight: "500",
  },
  priceFieldInput: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
    width: 150,
  },
  priceFieldContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  priceFieldRupee: {
    color: COLORS.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  priceFieldTextInput: {
    flex: 1,
    color: COLORS.navy,
    fontSize: 14,
    fontWeight: "500",
    padding: 0,
  },
  saveChangesButton: {
    borderRadius: 12,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    paddingVertical: 14,
    marginTop: 4,
    marginBottom: 16,
  },
  saveChangesButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  sheetHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sheetActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#1a2332",
    alignItems: "center",
    justifyContent: "center",
  },
  loginScrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 40,
    backgroundColor: COLORS.white,
  },
  loginWrapper: {
    width: "100%",
    maxWidth: 360,
    alignItems: "center",
  },
  loginHeader: {
    alignItems: "center",
    marginBottom: 32,
  },
  loginLogoBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: COLORS.teal,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 4,
  },
  loginLogoText: {
    color: COLORS.white,
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 34,
  },
  loginBrandOverline: {
    fontSize: 12,
    color: COLORS.muted,
    letterSpacing: 2,
    textTransform: "uppercase",
    fontWeight: "600",
  },
  loginBrandTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.navy,
    marginTop: 4,
  },
  loginCard: {
    width: "100%",
    backgroundColor: COLORS.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 6,
    overflow: "hidden",
  },
  loginCardContent: {
    padding: 24,
  },
  loginTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: COLORS.navy,
    textAlign: "center",
    marginBottom: 8,
  },
  loginSub: {
    fontSize: 13,
    color: COLORS.muted,
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 24,
  },
  loginErrorBox: {
    backgroundColor: "#ffe8e8",
    borderColor: "#fca5a5",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
  },
  loginErrorText: {
    color: "#cf3850",
    fontSize: 12,
    fontWeight: "500",
    textAlign: "center",
  },
  loginInputLabelContainer: {
    width: "100%",
    marginBottom: 6,
  },
  loginInputLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  loginPhoneRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  loginCountryBox: {
    width: 60,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
  },
  loginCountryInput: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.navy,
    width: "100%",
    textAlign: "center",
    padding: 8,
  },
  loginPhoneInputWrapper: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    justifyContent: "center",
  },
  loginPhoneInput: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.navy,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  loginPrimaryButton: {
    borderRadius: 12,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    shadowColor: COLORS.teal,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  loginPrimaryButtonPressed: {
    opacity: 0.9,
    backgroundColor: "#156868",
  },
  loginPrimaryButtonDisabled: {
    backgroundColor: "#a8c9c5",
    shadowOpacity: 0,
    elevation: 0,
  },
  loginPrimaryButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: "700",
  },
  loginSecuredNotice: {
    fontSize: 11,
    color: COLORS.muted,
    textAlign: "center",
    marginTop: 20,
  },
  loginBackButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    marginBottom: 20,
  },
  loginBackButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.teal,
  },
  loginOtpRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 24,
    gap: 6,
  },
  loginOtpBox: {
    flex: 1,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  loginOtpBoxFocused: {
    borderColor: COLORS.teal,
    borderWidth: 2,
  },
  loginOtpBoxError: {
    borderColor: "#fca5a5",
  },
  loginOtpBoxText: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.navy,
  },
  loginOtpCursor: {
    position: "absolute",
    width: 2,
    height: 20,
    backgroundColor: COLORS.teal,
  },
  loginHiddenOtpInput: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
  },
  loginTimerContainer: {
    alignItems: "center",
    marginTop: 20,
  },
  loginTimerText: {
    fontSize: 13,
    color: COLORS.muted,
  },
  loginResendButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  loginResendButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.teal,
  },
  loginTesterHelper: {
    width: "100%",
    marginTop: 32,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: "#f5f2ed",
  },
  loginTesterHelperTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.navy,
    marginBottom: 6,
  },
  loginTesterHelperText: {
    fontSize: 12,
    color: COLORS.muted,
    lineHeight: 18,
  },
  loginLogoutButton: {
    borderRadius: 10,
    backgroundColor: "#ffe5e8",
    borderColor: "#f3b2c0",
    borderWidth: 1,
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 20,
    marginBottom: 10,
  },
  loginLogoutButtonPressed: {
    backgroundColor: "#fca5a5",
  },
  loginLogoutButtonText: {
    color: "#9f1836",
    fontSize: 13,
    fontWeight: "600",
  },
  addBookingButtonPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.tealLight,
    borderWidth: 1,
    borderColor: COLORS.teal,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  addBookingButtonPillText: {
    color: COLORS.teal,
    fontSize: 11,
    fontWeight: "600",
  },
  bookingDetailsDisplay: {
    marginTop: 8,
    padding: 12,
    borderRadius: 10,
    backgroundColor: "#f4f7f6",
    borderWidth: 1,
    borderColor: "#d4e0da",
  },
  bookingDetailsText: {
    color: "#2c3e50",
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 8,
    fontWeight: "500",
  },
  bookedPriceSummary: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: "#d4e0da",
  },
  bookedPriceItem: {
    fontSize: 10,
    color: COLORS.muted,
    fontWeight: "600",
  },
  removeBookingButton: {
    alignSelf: "flex-start",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: "#ffebee",
    borderWidth: 0.5,
    borderColor: "#ef9a9a",
  },
  removeBookingButtonText: {
    color: "#c62828",
    fontSize: 11,
    fontWeight: "600",
  },
  addBookingFormContainer: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 10,
  },
  formTitle: {
    color: COLORS.navy,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 2,
  },
  formField: {
    gap: 4,
  },
  formLabel: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  formInput: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 13,
    color: COLORS.navy,
  },
  formInputMultiline: {
    minHeight: 60,
    textAlignVertical: "top",
  },
  formActionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 6,
  },
  formCancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#ebe8e3",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  formCancelButtonText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  formConfirmButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: COLORS.teal,
  },
  formConfirmButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  editBookingButton: {
    alignSelf: "flex-start",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: COLORS.tealLight,
    borderWidth: 0.5,
    borderColor: COLORS.teal,
  },
  editBookingButtonText: {
    color: COLORS.teal,
    fontSize: 11,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 40, 78, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalContent: {
    width: "100%",
    maxWidth: 480,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    maxHeight: "85%",
    shadowColor: COLORS.navy,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    overflow: "hidden",
  },
  modalScrollContent: {
    padding: 20,
    gap: 16,
  },
  modalFormHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebe9",
    paddingBottom: 12,
    marginBottom: 4,
  },
  modalHeaderSubtitle: {
    color: COLORS.teal,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
    textTransform: "uppercase",
  },
  bookedAmountHighlight: {
    color: COLORS.teal,
    fontWeight: "700",
  },
  formRowWithCounter: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  counterContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    height: 34,
    paddingHorizontal: 4,
  },
  counterButton: {
    width: 26,
    height: 26,
    borderRadius: 6,
    backgroundColor: "#ebe8e3",
    justifyContent: "center",
    alignItems: "center",
  },
  counterButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.teal,
  },
  counterValueInput: {
    width: 32,
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.navy,
    padding: 0,
  },
  notificationBellButton: {
    position: "relative",
    padding: 6,
    borderRadius: 999,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
  },
  notificationBellButtonActive: {
    borderColor: "#4a9f9f",
    backgroundColor: COLORS.tealLight,
  },
  notificationBadgeDot: {
    position: "absolute",
    top: 6,
    right: 7,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#cf3850",
    borderWidth: 1,
    borderColor: COLORS.white,
  },
  cruiseCardContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    position: "relative",
  },
  cruiseCardContainerPressed: {
    opacity: 0.9,
    borderColor: "#4a9f9f",
    backgroundColor: "#f5f0e6ee",
  },
  cruiseCardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  cruiseCardHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  cruiseCardTypeBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.tealLight,
    borderWidth: 1,
    borderColor: "#9dd8bc",
    alignItems: "center",
    justifyContent: "center",
  },
  cruiseCardTitle: {
    color: COLORS.navy,
    fontSize: 15,
    fontWeight: "700",
  },
  cruiseCardDivider: {
    height: 1,
    backgroundColor: "#e8ebe9",
    marginVertical: 10,
  },
  cruiseCardBody: {
    gap: 6,
  },
  cruiseCardInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cruiseCardIcon: {
    width: 14,
    textAlign: "center",
  },
  cruiseCardDateText: {
    color: "#0f284d",
    fontSize: 13,
    fontWeight: "500",
  },
  cruiseCardConfigText: {
    color: COLORS.muted,
    fontSize: 12,
  },
  cruiseCardPriceText: {
    color: COLORS.teal,
    fontSize: 13,
    fontWeight: "600",
  },
  cruiseCardActionsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e8ebe9",
  },
  cruiseCardChevronWrapper: {
    position: "absolute",
    right: 12,
    bottom: 12,
    opacity: 0.5,
  },
  detailPageRoot: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  detailScrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  detailCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    gap: 12,
  },
  detailHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  detailTitle: {
    color: COLORS.navy,
    fontSize: 18,
    fontWeight: "700",
  },
  detailSub: {
    color: COLORS.muted,
    fontSize: 13,
    marginTop: 2,
  },
  detailDivider: {
    height: 1,
    backgroundColor: "#e8ebe9",
    marginVertical: 4,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 4,
  },
  detailRowIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.tealLight,
    borderWidth: 1,
    borderColor: "#9dd8bc",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 2,
  },
  detailRowContent: {
    flex: 1,
  },
  detailRowLabel: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  detailRowValue: {
    color: "#0f284d",
    fontSize: 14,
    fontWeight: "500",
    marginTop: 2,
  },
  detailNotesBox: {
    backgroundColor: "#fdfbfa",
    borderColor: "#ebd8c4",
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginTop: 8,
  },
  detailNotesTitle: {
    color: "#8f6300",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  detailNotesText: {
    color: "#5c4d3c",
    fontSize: 13,
    lineHeight: 18,
  },

  // New components styles
  bold: { fontWeight: "700" },
  flexRow: { flexDirection: "row", alignItems: "center" },
  spaceBetween: { justifyContent: "space-between" },
  alignCenter: { alignItems: "center" },
  badgeContainer: { display: "flex", paddingHorizontal: 10, paddingVertical: 2, borderRadius: 999, fontSize: 11, fontWeight: "600" },
  statCardRow: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 16, padding: 18, flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  statCardRowAccent: { backgroundColor: "#FFF1F2", borderColor: "#FECDD3" },
  statCardRowLabel: { fontSize: 13, color: COLORS.navy, fontWeight: "600" },
  statCardRowLabelAccent: { color: "#991B1B" },
  statCardRowValue: { fontSize: 28, fontWeight: "700", color: COLORS.teal },
  statCardRowValueAccent: { color: COLORS.red },
  
  // Settings screens styles
  settingsToggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 11, paddingHorizontal: 18, borderTopWidth: 1, borderTopColor: COLORS.border },
  settingsGroupLabel: { fontSize: 11, fontWeight: "700", color: COLORS.teal, textTransform: "uppercase", letterSpacing: 0.5, paddingTop: 14, paddingHorizontal: 18, paddingBottom: 6 },
  
  // Finance screens styles
  financeHeaderTitle: { fontSize: 16, fontWeight: "700", color: COLORS.navy },
  financeHeaderSub: { fontSize: 12, color: COLORS.muted, marginTop: 2 },
  financeCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 20, paddingHorizontal: 18, paddingVertical: 16, marginBottom: 12 },
  financeStatCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 16, paddingHorizontal: 20, paddingVertical: 18, flex: 1, minWidth: 0, flexDirection: "column", justifyContent: "space-between", gap: 10 },
  financeCompletedPayoutsRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  financeCompletedPayoutsRowLast: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 10 },
  financeTableHead: { flexDirection: "row", paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: COLORS.border, marginBottom: 10 },
  financeTableHeadText: { fontSize: 10, fontWeight: "700", color: COLORS.muted },
  financeTableRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  financeTableRowLast: { flexDirection: "row", alignItems: "center", paddingVertical: 10 },
  financeSettingsSectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", paddingHorizontal: 18, paddingVertical: 16 },
  financeSettingsSectionTitle: { fontSize: 15, fontWeight: "700", color: COLORS.navy },
  financeSettingsSectionSubtitle: { fontSize: 12, color: COLORS.muted, marginTop: 2 },
  financeSettingsSectionDesc: { fontSize: 12, color: COLORS.muted, paddingHorizontal: 18, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  financeSettingsRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 18, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  financeSettingsRowLast: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 18, paddingVertical: 10 },
  financeSettingsEditBtnContainer: { paddingHorizontal: 18, paddingVertical: 14, borderTopWidth: 1, borderTopColor: COLORS.border },
  financeSettingsEditBtn: { display: "flex", flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderColor: COLORS.teal, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 7 },
  financeSettingsEditBtnText: { fontSize: 13, fontWeight: "700", color: COLORS.teal },
  
  // Reviews screens styles
  reviewsStatHeader: { flexDirection: "row", gap: 18, alignItems: "flex-start" },
  reviewsStatLabel: { fontSize: 40, fontWeight: "800", color: COLORS.navy, lineHeight: 40 },
  reviewsDistRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  reviewsDistNum: { fontSize: 11, fontWeight: "600", color: COLORS.muted, width: 16, textAlign: "right" },
  reviewsDistBarBg: { flex: 1, height: 6, backgroundColor: COLORS.border, borderRadius: 999, overflow: "hidden" },
  reviewsDistBarFg: { height: "100%", backgroundColor: COLORS.amber, borderRadius: 999 },
  reviewsDistCount: { fontSize: 11, color: COLORS.muted, width: 18, textAlign: "right" },
  reviewCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderLeftWidth: 3, borderLeftColor: "#7C3AED", borderRadius: 18, padding: 16 },
  reviewCardHeader: { flexDirection: "row", justifyContent: "space-between", gap: 10 },
  reviewCardGuestName: { fontWeight: "700", fontSize: 14, color: COLORS.navy },
  reviewCardDate: { fontSize: 12, color: COLORS.muted, marginTop: 2 },
  reviewCardTripType: { flexDirection: "row", alignItems: "center", gap: 5 },
  reviewCardBoatName: { fontSize: 13, fontWeight: "700", color: COLORS.navy, marginTop: 6 },
  reviewCardText: { fontSize: 13, color: COLORS.navy, lineHeight: 20, marginTop: 12 },
  
  // Legal screens styles
  legalDocCard: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border, borderRadius: 20, padding: 18, marginBottom: 12 },
  legalDocHeading: { fontSize: 16, fontWeight: "800", color: COLORS.navy, marginBottom: 10 },
  legalDocBody: { fontSize: 13, color: COLORS.muted, lineHeight: 22, textAlign: "justify" },
  legalDocItem: { borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: 10, marginTop: 10 },
  legalDocItemLabel: { fontSize: 12, fontWeight: "700", color: COLORS.teal, marginBottom: 4 },
  legalDocItemValue: { fontSize: 13, color: COLORS.muted, lineHeight: 20 },
  legalDocTable: { borderRadius: 12, overflow: "hidden", borderWidth: 1, borderColor: COLORS.border },
  legalDocTableHead: { flexDirection: "row", backgroundColor: COLORS.bg, paddingHorizontal: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  legalDocTableHeadText: { fontSize: 11, fontWeight: "700", color: COLORS.navy },
  legalDocTableRow: { flexDirection: "row", paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border, alignItems: "flex-start" },
  legalDocTableRowLast: { flexDirection: "row", paddingHorizontal: 12, paddingVertical: 10, alignItems: "flex-start" },
  legalDocBulletRow: { flexDirection: "row", gap: 8, marginTop: 8, alignItems: "flex-start" },
  legalDocBulletDot: { width: 5, height: 5, borderRadius: 2.5, backgroundColor: COLORS.teal, marginTop: 6 },
  legalDocBulletText: { fontSize: 13, color: COLORS.muted, lineHeight: 20 },
});

export default styles;
